#! /bin/sh
# Xsetup - run as root before the login dialog appears

#xconsole -geometry 480x130-0-0 -notify -verbose -fn fixed -exitOnFail -file /dev/xconsole &

now=$(date +%d-%m-%Y\ %T.%3N)

RED='\033[1;31m'
YEL='\033[1;33m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color
LOG_FILE=/var/log/eta.log
OPTICTOUCH_PID=/var/run/optictouch.pid

print_output() {
  now=$(date +%d-%m-%Y\ %T.%3N)
  echo "${NC}$now $1" >> $LOG_FILE
}

print_output "${RED}$0${NC}"
u=$(/usr/bin/whoami)
print_output "${RED}$0${NC} : running as ${YEL}$u${NC}"

if lsusb | grep -qE "(6615:0084|6615:0085|6615:0086|6615:0087|6615:0088|6615:0c20)" ; then
  print_output "${RED}$0${NC} : The IWB is PHASE 1 waiting handler"
  sleep 3
else
  print_output "${RED}$0${NC} : The IWB is PHASE 2 nothing to do in ${RED}$0${NC}"
fi

while [ ! -f $OPTICTOUCH_PID ]
do
    sleep 1
done
