#! /bin/sh
# Xstartup - run as root before session starts

RED='\033[1;31m'
YEL='\033[1;33m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color

LOG_FILE=/var/log/eta.log
KEYBOARD=eta-keyboard
KEYBOARD_INSTANCE=.virtualkeyboard

echo "${RED}$0${NC}" >> $LOG_FILE
u=$(/usr/bin/whoami)
echo "${RED}$0${NC} : running as ${YEL}$u${NC}" >> $LOG_FILE

if [ -e "/tmp/$KEYBOARD_INSTANCE" ]; then
    pid=$(pgrep $KEYBOARD)
    echo "${RED}$0${NC} : Terminating login keyboard gracefully" >> $LOG_FILE
    kill -9 $pid
    rm -rf /tmp/$KEYBOARD_INSTANCE
fi

PATH="$PATH:/usr/bin/X11"

if [ -e /etc/nologin ]; then
  # always display the nologin message, if possible
  if [ -s /etc/nologin ] && which xmessage > /dev/null 2>&1; then
    xmessage -file /etc/nologin -geometry 640x480
  fi
  if [ "$(id -u)" != "0" ] && \
     ! grep -qs '^ignore-nologin' /etc/kde4/kdm/kdm.options; then
    exit 1
  fi
fi

# NOTE: The session is aborted if the last command returns non-zero.

